import { JobClass } from "./class";

export class JobClassCollection {
    static get items() : Array<JobClass> { 
        return [
            new JobClass(0, 'Novice'),
            new JobClass(1, 'Swordman'),
            new JobClass(2, 'Mage'),
            new JobClass(3, 'Archer'),
            new JobClass(4, 'Acolyte'),
            new JobClass(5, 'Merchant'),
            new JobClass(6, 'Thief'),
            new JobClass(7, 'Knight'),
            new JobClass(8, 'Priest'),
            new JobClass(9, 'Wizard'),
            new JobClass(10, 'Blacksmith'),
            new JobClass(11, 'Hunter'),
            new JobClass(12, 'Assassin'),
            new JobClass(14, 'Crusader'),
            new JobClass(15, 'Monk'),
            new JobClass(16, 'Sage'),
            new JobClass(17, 'Rogue'),
            new JobClass(18, 'Alchemist'),
            new JobClass(19, 'Bard'),
            new JobClass(20, 'Dancer'),
            new JobClass(23, 'Super Novice'),
            new JobClass(24, 'Gunslinger'),
            new JobClass(25, 'Ninja'),

            
            new JobClass(4001, 'High Novice'),
            new JobClass(4002, 'High Swordman'),
            new JobClass(4003, 'High Mage'),
            new JobClass(4004, 'High Archer'),
            new JobClass(4005, 'High Acolyte'),
            new JobClass(4006, 'High Merchant'),
            new JobClass(4007, 'High Thief'),
            new JobClass(4008, 'High Knight'),
            new JobClass(4009, 'High Priest'),
            new JobClass(4010, 'High Wizard'),
            new JobClass(4011, 'Whitesmith'),
            new JobClass(4012, 'Sniper'),
            new JobClass(4013, 'Assassin Cross'),
            new JobClass(4015, 'Paladin'),
            new JobClass(4016, 'Champion'),
            new JobClass(4017, 'Professor'),
            new JobClass(4018, 'Stalker'),
            new JobClass(4019, 'Creator'),
            new JobClass(4020, 'Clown'),
            new JobClass(4021, 'Gypsy'),


            new JobClass(4023, 'Baby'),
            new JobClass(4024, 'Baby Swordman'),
            new JobClass(4025, 'Baby Mage'),
            new JobClass(4026, 'Baby Archer'),
            new JobClass(4027, 'Baby Acolyte'),
            new JobClass(4028, 'Baby Merchant'),
            new JobClass(4029, 'Baby Thief'),
            new JobClass(4030, 'Baby Knight'),
            new JobClass(4031, 'Baby Priest'),
            new JobClass(4032, 'Baby Wizard'),
            new JobClass(4033, 'Baby Blacksmith'),
            new JobClass(4034, 'Baby Hunter'),
            new JobClass(4035, 'Baby Assassin'),
            new JobClass(4037, 'Baby Crusader'),
            new JobClass(4038, 'Baby Monk'),
            new JobClass(4039, 'Baby Sage'),
            new JobClass(4040, 'Baby Rogue'),
            new JobClass(4041, 'Baby Alchemist'),
            new JobClass(4042, 'Baby Bard'),
            new JobClass(4043, 'Baby Dancer'),
            new JobClass(4045, 'Super Baby'),


            new JobClass(4046, 'Taekwon'),
            new JobClass(4047, 'Star Gladiator'),
            new JobClass(4049, 'Soul Linker'),
            new JobClass(4050, 'Gangsi'),
            new JobClass(4051, 'Death Knight'),
            new JobClass(4052, 'Dark Collector'),


            new JobClass(4054, 'Rune Knight'),
            new JobClass(4055, 'Warlock'),
            new JobClass(4056, 'Ranger'),
            new JobClass(4057, 'Arch Bishop'),
            new JobClass(4058, 'Mechanic'),
            new JobClass(4059, 'Guillotine Cross'),
            new JobClass(4060, 'Transcendent Rune Knight'),
            new JobClass(4061, 'Transcendent Warlock'),
            new JobClass(4062, 'Transcendent Ranger'),
            new JobClass(4063, 'Transcendent Arch Bishop'),
            new JobClass(4064, 'Transcendent Mechanic'),
            new JobClass(4065, 'Transcendent Guillotine Cross'),
            new JobClass(4066, 'Royal Guard'),
            new JobClass(4067, 'Sorcerer'),
            new JobClass(4068, 'Minstrel'),
            new JobClass(4069, 'Wanderer'),
            new JobClass(4070, 'Sura'),
            new JobClass(4071, 'Genetic'),
            new JobClass(4072, 'Shadow Chaser'),
            new JobClass(4073, 'Transcendent Royal Guard'),
            new JobClass(4074, 'Transcendent Sorcerer'),
            new JobClass(4075, 'Transcendent Minstrel'),
            new JobClass(4076, 'Transcendent Wanderer'),
            new JobClass(4077, 'Transcendent Sura'),
            new JobClass(4078, 'Transcendent Genetic'),
            new JobClass(4079, 'Transcendent Shadow Chaser'),


            new JobClass(4096, 'Baby Rune Knight'),
            new JobClass(4097, 'Baby Warlock'),
            new JobClass(4098, 'Baby Ranger'),
            new JobClass(4099, 'Baby Arch Bishop'),
            new JobClass(4100, 'Baby Mechanic'),
            new JobClass(4101, 'Baby Guillotine Cross'),
            new JobClass(4102, 'Baby Royal Guard'),
            new JobClass(4103, 'Baby Sorcerer'),
            new JobClass(4104, 'Baby Minstrel'),
            new JobClass(4105, 'Baby Wanderer'),
            new JobClass(4106, 'Baby Sura'),
            new JobClass(4107, 'Baby Genetic'),
            new JobClass(4108, 'Baby Shadow Chaser'),

            
            new JobClass(4211, 'Kagerou'),
            new JobClass(4212, 'Oboro'),
            new JobClass(4215, 'Rebellion'),
            new JobClass(4218, 'Summoner'),

            new JobClass(4220, 'Baby Summoner'),
            new JobClass(4222, 'Baby Ninja'),
            new JobClass(4223, 'Baby Kagero'),
            new JobClass(4224, 'Baby oboro'),
            new JobClass(4225, 'Baby taekwon'),
            new JobClass(4226, 'Baby Star Gladiator'),
            new JobClass(4227, 'Baby Soul Linker'),
            new JobClass(4228, 'Baby Gunslinger'),
            new JobClass(4229, 'Baby Rebellion'),
            new JobClass(4239, 'Star Emperor'),
            new JobClass(4240, 'Star Soul Reaper'),
            new JobClass(4241, 'Baby Star Emperor'),
            new JobClass(4242, 'Baby Soul Reaper'),

        ];
    }
}